version: "3.9"
services:
    database:
        image: mysql:5.7-debian
        platform: linux/amd64
        container_name: database
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: auto-register
            MYSQL_USER: auto
            MYSQL_PASSWORD: autoregister!@#
        healthcheck:
            test: [ 'CMD-SHELL', 'auto-register ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD' ]
            interval: 10s
            timeout: 2s
            retries: 100
        ports:
            - 3306:3306

    web:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            database:
                condition: service_healthy
        restart: always



